global:
  scrape_interval: 5s
  external_labels:
    monitor: 'prakash-monitor'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['172.24.55.155:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.24.55.155:9100']
